# Generated by Django 4.2.5 on 2023-10-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirm_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
    ]
