# Generated by Django 4.2.5 on 2023-09-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course_app/', verbose_name='превью (картинка)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='название урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course_app/', verbose_name='превью (картинка)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание урока')),
                ('video_link', models.TextField(blank=True, null=True, verbose_name='ссылка на видео')),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='course_app.course', to_field='title', verbose_name='из курса')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
