# Generated by Django 4.2.5 on 2023-09-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'оплата', 'verbose_name_plural': 'оплата'},
        ),
    ]
