# Generated by Django 4.2.5 on 2023-10-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_alter_payment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='lesson',
        ),
    ]
