# Generated by Django 4.2.5 on 2023-10-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_remove_payment_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='контактный email')),
                ('surname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client', null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.client', to_field='email', verbose_name='клиент-плательщик'),
        ),
    ]
