# Generated by Django 4.2.5 on 2023-10-06 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_app', '0006_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='клиент-плательщик'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
