# Generated by Django 4.2.5 on 2023-10-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_app', '0007_alter_payment_client_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='подписан')),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='course_app.course', to_field='title', verbose_name='курс подписки')),
                ('subscriber', models.ForeignKey(db_column='subscriber', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='подписчик')),
            ],
            options={
                'verbose_name': 'подписка на курс',
                'verbose_name_plural': 'подписки на курсы',
            },
        ),
    ]
