# Generated by Django 4.2.5 on 2023-10-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='active',
            new_name='is_active',
        ),
    ]
