# Generated by Django 4.2.5 on 2023-10-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_rename_active_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('add', 'создана'), ('success', 'успешно оплаченo'), ('fail', 'оплата не удалась')], default='add', max_length=50, verbose_name='статус оплаты'),
        ),
    ]
