# Generated by Django 4.2.5 on 2023-10-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id в системе stripe'),
        ),
    ]
