# Generated by Django 4.2.5 on 2023-10-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0011_payment_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_id',
            new_name='link_for_payment',
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена в Stripe'),
        ),
    ]
