# Generated by Django 4.2.5 on 2023-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0012_rename_stripe_id_payment_link_for_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='link_for_payment',
        ),
        migrations.AddField(
            model_name='course',
            name='link_for_payment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ссылка для оплаты в системе stripe'),
        ),
    ]
