# Generated by Django 4.2.5 on 2023-10-17 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_app', '0013_remove_payment_link_for_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='course_app.course', to_field='title', verbose_name='курс подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(db_column='subscriber', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='подписчик'),
        ),
    ]
