# Generated by Django 4.2.5 on 2023-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0014_alter_subscription_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stripe_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена в Stripe'),
        ),
    ]
